baseurl: ""
url: "http://gogoogle.top"
title: Go! Google Top !!
ico_url: /img/google.ico
description: google always good　　__craete by sherlock
#about me:
website: "http://bakerstreet.top"
mywebiste: "http://sherlock.help"
email: sherlock@bakerstreet.top
github: "https://github.com/bakerstreettop"